---
title: "Pronóstico De Índices Financieros"
author: "Adrián Rodríguez Amaya & Katherin Juliana Quiñones Losada"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
output: bookdown::gitbook
---

# Descargo De Responsabilidad {-}

La información consignada dentro de este libro se presenta solo para fines educativos. No constituye ninguna oferta, recomendación o solicitud para que ninguna persona realice una transacción, negociación o inversión, ni constituye una predicción de probable movimiento futuro en los índices financieros que sean presentados en cualquier ilustración o mencionados textualmente dentro del libro.

Las personas con acceso al presente libro deben buscar asesoramiento profesional sobre la idoneidad de invertir en valores, instrumentos financieros o estrategias de inversión. Las opiniones, proyecciones y estimaciones consignadas en este libro están sujetas a cambios sin previo aviso.

ADRIAN MAURICIO RODRIGUEZ AMAYA y KATHERIN JULIANA QUIÑONES LOSADA no son asesores de inversiones y no pretende brindarle asesoramiento sobre inversiones, legal o fiscal y no es responsable de ninguna pérdida que surja de cualquier inversión basada en una recomendación percibida.

