---
title: "Pronóstico De Índices Financieros"
author: "Adrián Rodríguez Amaya & Katherin Juliana Quiñones Losada"
date: "2023-04-18"
output: html_document
---

<style>
/* Clase para justificar el texto */.texto-justificado {
  text-align: justify;
}
</style>


<hr>
<h1><p align='center'>Descargo De Responsabilidad</p></h1>
<hr>

<div class="texto-justificado">

La información consignada dentro de este libro se presenta solo para fines educativos. No constituye ninguna oferta, recomendación o solicitud para que ninguna persona realice una transacción, negociación o inversión, ni constituye una predicción de probable movimiento futuro en los índices financieros que sean presentados en cualquier ilustración o mencionados textualmente dentro del libro. 


Las personas con acceso al presente libro deben buscar asesoramiento profesional sobre la idoneidad de invertir en valores, instrumentos financieros o estrategias de inversión. Las opiniones, proyecciones y estimaciones consignadas en este libro están sujetas a cambios sin previo aviso.


ADRIAN MAURICIO RODRIGUEZ AMAYA y KATHERIN JULIANA QUIÑONES LOSADA no son asesores de inversiones y no pretende brindarle asesoramiento sobre inversiones, legal o fiscal y no es responsable de ninguna pérdida que surja de cualquier inversión basada en una recomendación percibida. 

</div>

<br>

<hr>
<h1><p align='center'>Pronóstico De Índices Financieros</p></h1>
<hr>

<div class="texto-justificado">

El presente libro pretende realizar un ejercicio académico relacionado con el pronóstico de los precios de índices financieros. La información será obtenida a través de la API de Yahoo Finance .

Para ser más exactos nos interesa analizar y trabajar en los retornos a partir de precios de cierre de diferentes acciones en la etapa pre y post pandemia (Ene 2019- Dic 2021). En Yahoo Finance podemos encontrar diferentes acciones asociados a diferentes índices. Para poder acotar el ejercicio nos centraremos en trabajar sobre uno de los índices mas populares a nivel mundial como es el S&P 500 (Standard and Poor’s 500).

El S&P 500, aunque incluye 500 compañías de gran tamaño en Estados Unidos, no se puede asegurar con completa certeza que son las 500 mas grandes. Estas 500 empresas deben cumplir diferentes normas regulatorias, que van desde cotizar inicialmente en índices como NASDAQ, como la capitalización bursátil debe superar los 6.100 millones de dólares (este valor se suele ajustar cada año).
S&P trabaja en función de la representación de la industria, el tamaño de la empresa, el número de accionistas, el volumen de negociación y la solidez financiera.

Standard and Poor's afirma que utiliza el requisito de solidez financiera para garantizar la estabilidad del Índice y que este requisito se basa únicamente en información disponible públicamente.[2]

La composición por sector dentro de este índice, se distribuye en un 26%  del sector de tecnología; el 14% corresponde al sector financiero, el sector salud 13,9% consumo discrecional 12,9%, industria 9,9%, consumo masivo 6,7%, energía 6,3%, materiales, 2,8%, servicios públicos 2,8%, real estate 2,7%, y telecomunicaciones el restante 1,8%.

Entre algunas empresas que se destacan se encuentran APPLE, AMAZON, FACEBOOK, entre otras. Este indicador es popular por proveer al inversionista, una cartera diversificada y de bajo riesgo, lo cual suena bastante positivo para un inversor con perfil de riesgo bajo.[3]

Ahora bien, el interés en este tipo de datos, nace de identificar el reto que representa trabajar con datos tan volátiles como puede llegar a representar los precios de cierre de las acciones. Estos datos requerirán un fuerte análisis exploratorio para identificar patrones, tendencias y diferentes conceptos asociados a series de tiempo que deben evaluarse de manera previa y a profundidad, para lograr un proceso de modelado ideal. Posteriormente, nos enfocaremos en hacer uso de pronósticos con el fin de establecer futuros comportamientos del retorno de las acciones correspondientes al índice S&P 500. Dentro del desarrollo del ejercicio académico se harán definiciones que permitan acotar el entregable como por el ejemplo, el número de empresas a trabajar, el número de días a predecir, las variables explicativas a trabajar (univariado o multivariado, como uso del PIB de USA, precio del dólar, entre otros).

Además, quisiéramos evaluar como las técnicas tradicionales (métodos estadísticos) se comportan versus técnicas mas recientes como las de Machine Learning (ML). Nuestro objetivo no es descartar una herramienta o la otra, nuestro objetivo es poder identificar las bondades de cada una en la aplicación de series de tiempo en nuestra vida profesional y/o académica.

El pronóstico calculado nos permitirá descubrir el valor futuro de del valor de las acciones de una empresa en particular; esto permitirá tanto a los inversores como a las empresas tomar decisiones oportunas frente a las dinámicas del negocio.

</div>


![J. Smialek, « Fastest Inflation in 31 Years Puts More Heat on Washington» 2021. [En línea]. Disponible en: https://www.nytimes.com/2021/11/10/business/economy/consumer-price-inflation-october.html. [Consultado: Jun. 17, 2022].](./inflation-600.png)


<br>

<hr>
<h1><p align='center'>Referencias</p></h1>
<hr>

[1] https://finance.yahoo.com

[2] W. B. Elliot, B. F. Van Ness y M. Walker, «What drives the S&P 500 inclusion effect? An analytical survey,» Financial Managment, vol. 35, nº 4, pp. 31-48, 2006. 

[3] Wilson y C. Jones, «An analysis of the S&P 500 index and Cowles’s extensions: Price indexes and stock returns,» The Journal of Business, vol. 75, nº 3, pp. 505-533, 2002. 
